version: '3'
services:
  db:
    image: mongo:latest
    expose:
      - 27017
    restart: always
  app:
    build: .
    ports:
      - 3000:3000
    restart: always
    environment:
      MONGODB_URI: 'mongodb://db:27017/mestodb'
    links:
      - db
